lib/Element.php, lib/Element/Base.php, lib/Element/Cdata.php, lib/Element/Elements.php, lib/Element/KeyValue.php, lib/Element/Uri.php, lib/LibXMLException.php, lib/ParseException.php, lib/Reader.php, lib/Service.php, lib/Writer.php, lib/XmlDeserializable.php, tests/Sabre/XML/Element/Eater.php
Hi Evert,
Please note that you may wish to simply drop the copyright notice from the [generic license](http://sabre.io/license/), or at least update the last year there too.
=> Drop reference to moved project

lib/Reader.php
Otherwise it is possible to perform requests to other domains, gaining access to local file resources seems not possible.
Following XML will perform a request to http://owncloud.org when the loader is enabled which is especially of relevance due to https://bugs.php.net/bug.php?id=64938.
```xml
<?xml version="1.0" encoding="utf-8" standalone='no'?>
<!DOCTYPE books [
<!ENTITY % e1fe9 SYSTEM "http://owncloud.org">%e1fe9; ]>
<books
xmlns="http://example.org/books">
<book>
<title>Snow Crash</title>
<author>Neil Stephenson</author>
</book>
<book>
<title>Dune</title>
<author>Frank Herbert</author>
</book>
</books>
```
@evert THX
=> Disable entity loader

lib/Reader.php
Corrected phpdocs return type of Sabre\Xml\Reader::parseAttributes so my IDE stops whining about.
=> Improved phpdocs return type in Reader::parseAttributes

lib/ContextStackTrait.php, lib/Service.php, lib/Writer.php, tests/Sabre/Xml/WriterTest.php
cc: @staabm. What do you think?
=> External object serializers.

composer.json, lib/functions.php, tests/Sabre/XML/FunctionsTest.php
didnt found the comments in which we discussed this topic therefore starting from scratch.
hopefully all points are adressed.
=> added a new namespaceAware() deserializer function

CHANGELOG.md, composer.json, lib/Service.php, lib/deserializers.php, lib/serializers.php, tests/Sabre/Xml/ServiceTest.php
added popo mapping on the Service class.
see enclosed test how it is expected to work.
its more or less the same as initially discussed in https://github.com/fruux/sabre-xml/pull/61
After we finished the impl. details I will iterate over the phpdocs a bit.
=> added popo serializer/deserializer and Service shorthand

lib/deserializers.php, tests/Sabre/Xml/DeserializersTest.php
This is a feature for VO's such as this:
class VO {
public $foo = [];
}
Specifying the empty array as the default will cause the parser to
assume that foo may appear more than once and append elements to the
array.
cc: @staabm
=> Automatically support VO properties that are specified as arrays.

tests/Sabre/Xml/Deserializer/EnumTest.php
The old function names might irritate people.
=> Fix function names in Deserializer/EnumTest

lib/Service.php
When serializing large xml documents the cost parsing of the namespaces from clark notation becomes a significant portion (>10%) of the serialization cost.
Since most xml documents will only use a fairly small number of xml elements we're better of keeping the parsed version of the namespace/element around for reuse.
This saves doing a regex (and some memory allocations) for each element we serialize
[comparison](https://blackfire.io/profiles/compare/4449f8f7-abbc-4b7d-89a4-a3770e75b053/graph)
cc @evert
=> Cache namespaces parsed from clark notation

.travis.yml
We dont use xdebug features in travis, therefore disabling it which speeds up build considerably.
=> Disable xdebug for composer install to speedup build

lib/Reader.php
this are edge-cases but still those should restore the proper context of the current reader.
I didnt experience a concrete problems with this but just stumbled across it while reading the code.
Thats why no unit test provided.
Feel free to close this without merging it in case you think its not worth it.
=> restore reader-context in early-return paths

composer.json
=> Fix: Remove empty bin section from composer.json

lib/Service.php
This function returns a string, but the PHPDoc comment currently says it returns void.
=> set correct return type

lib/Service.php
To make https://github.com/etsy/phan happy:
```
apps/dav/lib/CardDAV/SyncService.php:255 PhanNonClassMethodCall Call to method getResponses on non-class type void
apps/dav/lib/CardDAV/SyncService.php:259 PhanNonClassMethodCall Call to method getSyncToken on non-class type void
```
=> [master] Fix invalid PHPDocs

CHANGELOG.md, lib/Deserializer/functions.php, tests/Sabre/Xml/Deserializer/EnumTest.php, tests/Sabre/Xml/Deserializer/KeyValueTest.php, tests/Sabre/Xml/ServiceTest.php
=> [2.1] Prevent infinite loop on empty xml elements

CHANGELOG.md, lib/Deserializer/functions.php, tests/Sabre/Xml/Deserializer/EnumTest.php, tests/Sabre/Xml/Deserializer/KeyValueTest.php, tests/Sabre/Xml/ServiceTest.php
=> [1.5] Prevent infinite loop on empty xml elements

lib/Service.php, tests/Sabre/Xml/ServiceTest.php
When input retrieved from stream_get_contents
is empty string, then it would be safe to return
from the parse and expect methods.
Signed-off-by: Sujith H <sharidasan@owncloud.com>
=> Throw exception when empty inputs found

.gitignore, .php_cs.dist, .travis.yml, composer.json, lib/LibXMLException.php, lib/Reader.php, lib/Serializer/functions.php, lib/Service.php, lib/Writer.php, phpstan.neon, tests/Sabre/Xml/Element/Eater.php, tests/Sabre/Xml/Element/Mock.php, tests/phpunit.xml
- drop PHP 7.0
- move to phpunit 7
- use later phpstan
- run php-cs-fixer in CI
=> Update dependencies and tooling

lib/Service.php, tests/Sabre/Xml/ServiceTest.php
PR https://github.com/sabre-io/xml/pull/166 is incomplete. It still allows this situation to happen in an infinite loop:
```
XMLReader::XML(): Empty string supplied as input at \/Users\/mrow4a\/Projects\/www\/octest\/lib\/composer\/sabre\/xml\/lib\/Reader.php#63
XMLReader::read(): Load Data before trying to read at \/Users\/mrow4a\/Projects\/www\/octest\/lib\/composer\/sabre\/xml\/lib\/Reader.php#63
XMLReader::read(): Load Data before trying to read at \/Users\/mrow4a\/Projects\/www\/octest\/lib\/composer\/sabre\/xml\/lib\/Reader.php#63
...
```
With this MR, now I see exception properly handled:
```
Exception: {\"Exception\":\"Sabre\\\\
Xml\\\\ParseException\",\"Message\":\"The input element to parse is empty. Do not attempt to parse\",\"Code\":0,\"Trace\":\"#0 …
```
=> xml cannot be empty while reading

.travis.yml, composer.json, lib/Reader.php
1) sort out variables in `.travis.yml` for selecting to run php-cs-fixer, phpunit and phpstan
2) Add a matrix entry to run just phpunit on Ubuntu 20.04 "focal" with "nightly" PHP (which is the way to get PHP 8.0 at the moment)
3) When not running php-cs-fixer, explicitly remove it from `composer.json` (because php-cs-fixer does not yet support PHP 8.0, so composer cannot sort out dependencies if we have PHP 8.0 and php-cs-fixer 2.* together)
4) `libxml_disable_entity_loader` is deprecated on PHP 8.0. This is already disabled on PHP 8.0, so this function does not need to be called. Put a conditional check around it. https://php.watch/versions/8.0/libxml_disable_entity_loader-deprecation
Relates to https://github.com/sabre-io/vobject/pull/513
=> Test with PHP8.0

CHANGELOG.md, lib/Version.php
I forgot to do the changelog and `Version.php` bump before making the release for 2.2.2 - so 2.2.2 as `2.2.1` in `Version.php`
Fix this by making a 2.2.3 release that will have all the Changelog entries and will have `2.2.3` in `Version.php` - that will give a consistent/tidy release. It does not hurt that there will be 2.2.2 release then 2.2.3 an hour later.
=> Changelog and Version.php for 2.2.3

composer.json, lib/ParseException.php, tests/Sabre/Xml/Deserializer/FunctionCallerTest.php, tests/Sabre/Xml/Deserializer/KeyValueTest.php, tests/Sabre/Xml/Deserializer/ValueObjectTest.php
The latest php-cs-fixer finds some new things. Code changes were needed in https://github.com/sabre-io/dav/pull/1316 for `sabre/dav`. We might as well consistently make sure to use at least this version 2.17.1 in all repos so that we are doing consistent code-style checking.
=> Use latest php-cs-fixer 2.17.1

lib/Deserializer/functions.php, phpstan-baseline.neon
cs-fixer now finds a bit of PHP-doc to adjust.
phpstan no longer reports some false-positives - remove them from `ignoreErrors`
=> Adjust new things from cs-fixer and phpstan

CHANGELOG.md, lib/ContextStackTrait.php, lib/Deserializer/functions.php, lib/Serializer/functions.php, lib/Service.php
No functional change. This just cleans up some crud in comments that my IDE keeps telling me about. May as well do it so I don't have to see it any more.
=> Cleanup grammar in comments

composer.json
`sabre/xml` 3 already requires PHP 7.4 or later. So anyone who gets "given" `sabre/xml` 3 by composer has at least PHP 7.4.
`        "sabre/uri" : ">=1.0,<4.0.0"`
1) Is there any good reason to keep the mention of `sabre/uri` 1.0? It feels a bit odd to keep allowing people to use such an old version of `sabre/uri` with `sabre/xml`
Answer: dropped.
2) What version bump should we do in `sabre/xml` when we release this change - I guess someone might notice the Windows file path behavior change in `sabre/uri` if they auto-magically get the new major version. But they can also easily mention `sabre/uri` major version 2 in their own `composer.json` if they themselves depend on `sabre/uri` - so is the next `sabre/xml` just a patch, a minor or a major release?
Answer: I will release a new major …
=> Allow sabre/uri major version 3

CHANGELOG.md, lib/Version.php
`sabre/uri` major version 3 has a breaking change (which only applies to Windows-style URIs, but it is breaking for an installation that really uses that). So bump the major version here in `sabre/xml` so that consumers can choose exactly what combination of `sabre/xml` plus `sabre/uri` that they use.
It's a bit sad that I released 3.0.0 only a month ago, but the numbers are integers, and integers go on forever - we won't run out!
=> Prepare release 4.0.0

lib/LibXMLException.php, lib/ParseException.php, lib/Reader.php, lib/Serializer/functions.php, lib/Writer.php, phpstan-baseline.neon, tests/Sabre/Xml/ContextStack.php
php-cs-fixer is reporting these. I guess there has been a newer php-cs-fixer version released that is different.
It wants "root" classes and functions to use the leading `\` - `\DateTime`.
We could change some php-cs-fixer rule settings, but actually it is easy to accept these code-style changes.
=> Adjust code style to meet current php-cs-fixer

composer.json, lib/Element/Uri.php
I really just want to check that all of CI still passes (there have been minor version releases of the CI tools phpunit, phpstan and php-cs-fixer recently).
This PR updates the minor versions recorded in `composer.json`. That does not do anything exciting, but maybe it helps in the future that we know what minor version of each tool was known to work.
=> Bump require-dev dependencies

composer.json, lib/Deserializer/functions.php, lib/Element/Base.php, lib/ParseException.php, lib/Service.php, lib/Writer.php, lib/XmlDeserializable.php, tests/Sabre/Xml/Element/Eater.php, tests/Sabre/Xml/Element/Mock.php, tests/Sabre/Xml/Element/XmlFragmentTest.php
Adjust PHP doc etc. so that the latest php-cs-fixer and phpstan will pass.
Mostly cs-fixer removed various `mixed` type declarations for var, param, return. But then `phpstan` complained about things having their type declaration missing!
One workaround is to also put a description at the end of the type declaration. So I did that in some places.
I also specified the type better in one place.
=> Bump dependency versions

lib/Deserializer/functions.php, tests/Sabre/Xml/Deserializer/ValueObjectTest.php
This fixes a bug, when valueobject is an empty element like <foo></foo> In this situation the deserializer did read one more, thus ending up a level higher than required.
I have also attached a unit test to demonstrate the problem. With the original code this xml did throw an error.
=> Fixed error where valueobject has eaten too much

lib/Deserializer/functions.php, tests/Sabre/Xml/Deserializer/ValueObjectTest.php
This fixes a bug, when valueobject is an empty element like <foo></foo> In this situation the deserializer did read one more, thus ending up a level higher than required
Backport to v3 branch.
=> [v3] Fixed error where valueobject has eaten too much

lib/Deserializer/functions.php, tests/Sabre/Xml/Deserializer/ValueObjectTest.php
This fixes a bug, when valueobject is an empty element like <foo></foo> In this situation the deserializer did read one more, thus ending up a level higher than required
Backport PR #229 to 2.1 branch.
=> [2.1] Valueobject runaway v2.1

lib/Deserializer/functions.php, tests/Sabre/Xml/Deserializer/ValueObjectTest.php
This fixes a bug, when valueobject is an empty element like <foo></foo> In this situation the deserializer did read one more, thus ending up a level higher than required
Backport #229 to 2.2 branch
=> [2.2] Fixed error where valueobject has eaten too much

lib/Service.php
Fixes #237 
This makes the PHPdoc of Service write allow an array with integer keys to be passed in the `value` parameter.
That is passed to:
`$w->writeElement($rootElementName, $value);`
And Writer `writeElement` already has PHPdoc that allows `array<int|string, mixed>`
=> Enhance PHPdoc of Service write value parameter

lib/Deserializer/functions.php, lib/Element/Base.php, lib/Element/Uri.php, lib/Reader.php, lib/Service.php, lib/Writer.php, phpstan.neon, tests/Sabre/Xml/ContextStackTest.php, tests/Sabre/Xml/ServiceTest.php
This seems to be possible without breaking the code ;)
=> Increase phpstan from level 6 to level 8

composer.json, tests/phpunit.xml
1) `phpunit` reports:
Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!
Done with:
```
./vendor/phpunit/phpunit/phpunit  --configuration tests/phpunit.xml --migrate-configuration
```
2) Update the php-cs-fixer minor version to the current one. That is what runs today and passes. It is sometimes handy to know what is the latest that was passing.
=> Update CI and test things

.github/workflows/ci.yml, composer.json, tests/phpunit.xml
to keep it up-to-date in case we want to backport anything from master in future.
=> Update CI etc in v2

.github/workflows/ci.yml
to keep CI up-to-date in the 2.2 branch so that we caqn make future releases, if needed.
=> Bump actions to current versions

lib/Element/Elements.php, lib/Element/KeyValue.php, lib/Element/Uri.php, tests/Sabre/Xml/ServiceTest.php
=> fix: more return type declarations on xmlDeserialize

composer.json, lib/Deserializer/functions.php, lib/LibXMLException.php, lib/Reader.php, lib/Service.php, tests/Sabre/Xml/Element/XmlFragmentTest.php
php-cs-fixer 3.49 (or some recent minor release) wants to use the `?` (nullable) syntax on optional parameters.
That syntax has been supported for quite a while since PHP https://www.php.net/manual/en/migration71.new-features.php
In the cases here, as well as the default value of the parameter being `null`, the `?` explicitly allows the caller to pass the value `null` if they want.
This seems reasonable, I don't see how it can break any existing usage.
=> chore: use php-cs-fixer 3.49

lib/Service.php, lib/Writer.php, tests/Sabre/Xml/ServiceTest.php
while updating from a old version I got the impression that the first offset of `parseClarkNotation` cannot get null.
https://3v4l.org/Bo8q3
did I miss something?
=> More precise `parseClarkNotation` return type

lib/Deserializer/functions.php, tests/Sabre/Xml/Deserializer/ValueObjectTest.php
When encountering an element from another namespace the value object parser does skip the opening element. However when it encounters the closing element it did handle it like it was the closing element of the one being processed.
This commit and unit test fixes the issue by ignoring the element completely. Without the patch the unit test would not parse the `lastName` element.
This patch is against the branch `2.2`, because I'm still using this one, I hope it's not a problem. I've checked the `master` branch as well, and it should be straightforward to apply it there as well.
BTW: would it be possible to add mappings for multiple namespaces?
=> Fixed handling of elements from foreign namespaces in values object (2.2)

lib/Deserializer/functions.php, tests/Sabre/Xml/Deserializer/ValueObjectTest.php
When encountering an element from another namespace the value object parser does skip the opening element. However when it encounters the closing element it did handle it like it was the closing element of the one being processed.
This commit and unit test fixes the issue by ignoring the element completely
This is a port of #270 to the v3 branch.
Also see #273 which has the same code applied to the master branch.
=> Fixed handling of elements from foreign namespaces in values object (v3)

lib/Deserializer/functions.php, tests/Sabre/Xml/Deserializer/ValueObjectTest.php
When encountering an element from another namespace the value object parser does skip the opening element. However when it encounters the closing element it did handle it like it was the closing element of the one being processed.
This commit and unit test fixes the issue by ignoring the element completely
Foward-port of #270 to master.
This works nicely. If I locally remove the code added to `lib/Deserializer/functions.php` and run the unit tests, the new test fails with:
```
$ composer phpunit
> phpunit --configuration tests/phpunit.xml
PHPUnit 9.6.19 by Sebastian Bergmann and contributors.
.............F.................................................  63 / 113 ( 55%)
..................................................              113 / 113 (100%)
Time: 00:00.068, Memory: 8.00 MB …
```
=> Fixed handling of elements from foreign namespaces in values object (master)

lib/Service.php, lib/Writer.php, tests/Sabre/Xml/ServiceTest.php
Backport PR #272 to v3 branch
And adjust namespace check because it cannot be null - this happened in master as part of PR #251 "Increase phpstan from level 6 to level 8". We don't want to backport all those changes to v3, but we do need this little change so that `phpstan` will pass.
=> More precise parseClarkNotation return type (v3)

.gitattributes
=> Stop exporting php-cs-fixer config

.github/workflows/ci.yml, composer.json, lib/LibXMLException.php, lib/Reader.php, lib/Service.php, phpstan.neon
Related issue https://github.com/sabre-io/event/issues/123
- keep running cs-fixer just on the oldest supported PHP 7.1 (it does a little bit different spacing for call-by-reference parameters if I run it in PHP 8)
- run phpstan in both PHP 7.1 and PHP 8.4 to (hopefully) find all the "interesting" things
- adjust nullable parameters to explictly have the `?` to keep PHP 8.4 happy
- - turn off `reportUnmatchedIgnoredErrors` in PHPstan. PHPstan, when run in PHP 7.1, thinks that a call to `startElementNs` has a problem. But, when run with PHP 8.4, it correctly understands that the call is fine. So we don't want to report the unmatched ignored error.
- specify the current minor version of PHP 9 (9.6) just so that it is explicit that 9.6.x should be used
=> Add PHP 8.4 compliance for 2.2 branch

lib/Deserializer/functions.php
Some occurences were missed.
~I did not pushed the fixes yet, I want to first check if the updated PHPStan configuration will help to detect them.~ I do not know how to detect them in the CI.
=> Explicitly mark nullable parameter

.github/workflows/ci.yml, .gitignore, .php-cs-fixer.dist.php, composer.json, lib/Deserializer/functions.php, lib/Element/Base.php, lib/Element/Elements.php, lib/Element/KeyValue.php, lib/Element/Uri.php, lib/Element/XmlFragment.php, lib/LibXMLException.php, lib/ParseException.php, lib/Reader.php, lib/Serializer/functions.php, lib/Service.php, lib/Version.php, lib/Writer.php, lib/XmlDeserializable.php, tests/Sabre/Xml/Element/Eater.php, tests/Sabre/Xml/Element/Mock.php, tests/Sabre/Xml/Element/XmlFragmentTest.php, tests/Sabre/Xml/ReaderTest.php, tests/Sabre/Xml/ServiceTest.php, tests/Sabre/Xml/WriterTest.php
Add the ability to use php-cs-fixer major version 3.
Add `.php-cs-fixer.dist.php` (the settings of php-cs-fixer for major version 3) and put the `nullable_type_declaration` check into it.
Run cs-fixer on PHP 8.4.
Leave the old cs-fixer still running on PHP 7.1.
And run cs-fixer on every PHP version, to be sure. In CI, `composer` will choose whether to use major version 2 or 3 of php-cs-fixer.
The newer cs-fixer v3 makes various nice fixes that do not break on PHP 7.1.
The old cs-fixer v2 is happy with the changes, it does not try to change them back - that is nice.
This is only needed for this old release series that still has PHP 7.1 support. We can run both cs-fixer and phpstan (and phpunit) on PHP 7.1 through 8.4. I think that helps give confidence that the code works across that range …
=> chore: add cs-fixer v3

.github/workflows/ci.yml, .php-cs-fixer.dist.php, composer.json, lib/ContextStackTrait.php, lib/Writer.php
I have taken the various CI and tooling changes from 2.2 and applied them here to the v3 branch.
There is not much code change needed - most of the real changes needed for 8.4 are already in the v3 branch. But this gets CI running on PHP 8.4 to confirm that.
=> Add PHP 8.4 compliance for v3 branch

.github/workflows/ci.yml, .php-cs-fixer.dist.php, composer.json, lib/ContextStackTrait.php, lib/Service.php, lib/Writer.php, tests/Sabre/Xml/ServiceTest.php
Apply the small code changes and the CI and tooling changes for PHP 8.4 to master (which is where the v4 release series comes from).
And fixup `parse()` and `expect()` functions in `Service.php` - see the comments below about what `phpstan` noticed.
Now, if someone passes a closed resource, we will throw the usual `ParseException` that is thrown when someone passes an empty input.
=> Add PHP 8.4 compliance for v4

composer.json, lib/Service.php, phpstan.neon, tests/Sabre/Xml/ServiceTest.php
Backport the code related to issue #297 from PR #296 to the 2.2 branch.
~And apply code-style changes that the latest php-cs-fixer 3.64 makes.~
php-cs-fixer 3.64 wants to apply trailing-comma to `list(a,b,c,)` as part of the latest `Symfony` code style.
The old php-cs-fixer v2 does not know about that.
So for this 2.2 branch we can lock the new php-cs-fixer to 3.63.2 so that it does not do any code-style changes.
That lets the CI pass.
In future we will probably drop the support for PHP 7.1 7.2 7.3 and therefore can stop using php-cs-fixer v2. I will do that for a 2.3 series "some day".
=> Backport fix for "Passing a closed resource to Service parse or expect" to 2.2

lib/Service.php, tests/Sabre/Xml/ServiceTest.php
Backport the code related to issue #297 from PR #296 to the v3 branch.
=> Backport fix for "Passing a closed resource to Service parse or expect" to v3

.github/workflows/ci.yml
this gives a chance to confirm that CI is still passing using the current releases of the dev tools used in CI.
=> chore(ci): update github workflow actions to latest versions
