CHANGELOG.md, lib/Reader.php, tests/Sabre/Xml/ReaderTest.php
=> Handle broken xml better.

lib/Element/XmlFragment.php, lib/Reader.php
This pull request removes two variables that are initialized but never used.
=> Remove unused variables

lib/deserializers.php, tests/Sabre/Xml/DeserializersTest.php
=> Fix infinite loop on unknown elements in VO's.

lib/Service.php, tests/Sabre/Xml/ServiceTest.php
=> Added writeValueObject.

lib/Element/Elements.php, lib/Writer.php, lib/deserializers.php, lib/serializers.php, tests/Sabre/Xml/Deserializer/EnumTest.php, tests/Sabre/Xml/Deserializer/KeyValueTest.php, tests/Sabre/Xml/Deserializer/RepeatingElementsTest.php, tests/Sabre/Xml/Deserializer/ValueObjectTest.php, tests/Sabre/Xml/Serializer/EnumTest.php, tests/Sabre/Xml/Serializer/RepeatingElementsTest.php, tests/Sabre/Xml/WriterTest.php
=> Refactoring the default serialization behavior.

lib/Deserializer/functions.php, lib/Reader.php, lib/Service.php
=> Fix: CS issues

.travis.yml
=> Fix: Sort out Travis configuration

lib/Deserializer/functions.php, tests/Sabre/Xml/Deserializer/MixedContentTest.php
=> added a mixedContent deserializer

lib/Service.php
Signed-off-by: Lukas Reschke <lukas@statuscode.ch>
=> [1.5] Fix invalid PHPDocs

CHANGELOG.md, lib/Deserializer/functions.php, tests/Sabre/Xml/Deserializer/EnumTest.php, tests/Sabre/Xml/Deserializer/KeyValueTest.php, tests/Sabre/Xml/ServiceTest.php
=> [2.0] Prevent infinite loop on empty xml elements

lib/Service.php
=> first attempt

.gitignore, composer.json, tests/Sabre/Xml/ContextStackTest.php, tests/Sabre/Xml/Deserializer/KeyValueTest.php, tests/Sabre/Xml/Element/CDataTest.php, tests/Sabre/Xml/ReaderTest.php, tests/Sabre/Xml/ServiceTest.php, tests/Sabre/Xml/WriterTest.php
See last commit.
This is on top of #173
=> Use phpunit8

.gitignore, .travis.yml, composer.json, tests/Sabre/Xml/ContextStackTest.php, tests/Sabre/Xml/ServiceTest.php, tests/phpunit.xml
- cleanup `.gitignore`
- implement Travis like in `skel` (separate `phpstan` job, `--prefer-lowest` in matrix)
- refactor some test code so that `phpstan` is happy
=> Standardize CI 20200203

CHANGELOG.md, lib/Version.php
closes https://github.com/sabre-io/xml/issues/184
=> Release 2.2.1

CHANGELOG.md, lib/Version.php
I forgot to do that before creating the release!
=> Add changelog and Version.php bump for 2.2.2

CHANGELOG.md, lib/Version.php
I forgot to bump the VERSION number and put the changes into CHANGELOG.md.
I will need to do another release and bump VERSION again in order to get a release done with a matching VERSION
=> Changes that should have happened for 2.2.4

CHANGELOG.md, lib/Version.php
bump to 2.2.5 so that I can release 2.2.5 to fix this
=> version bump that was missed in 2.2.4

.github/workflows/ci.yml, lib/Service.php
and the latest php-cs-fixer wants to change the order of some PHPdoc comments, so let it do it.
=> Add PHP 8.2 to CI

tests/Sabre/Xml/ContextStackTest.php, tests/Sabre/Xml/Deserializer/EnumTest.php, tests/Sabre/Xml/Deserializer/FunctionCallerTest.php, tests/Sabre/Xml/Deserializer/KeyValueTest.php, tests/Sabre/Xml/Deserializer/MixedContentTest.php, tests/Sabre/Xml/Deserializer/RepeatingElementsTest.php, tests/Sabre/Xml/Deserializer/ValueObjectTest.php, tests/Sabre/Xml/Element/CDataTest.php, tests/Sabre/Xml/Element/ElementsTest.php, tests/Sabre/Xml/Element/KeyValueTest.php, tests/Sabre/Xml/Element/UriTest.php, tests/Sabre/Xml/Element/XmlFragmentTest.php, tests/Sabre/Xml/InfiniteLoopTest.php, tests/Sabre/Xml/ReaderTest.php, tests/Sabre/Xml/Serializer/EnumTest.php, tests/Sabre/Xml/Serializer/RepeatingElementsTest.php, tests/Sabre/Xml/ServiceTest.php, tests/Sabre/Xml/WriterTest.php
See discussion in https://github.com/sabre-io/cache/pull/49
=> Call static assert functions with self::

lib/Service.php
See description in PR #247 
Fixes #237 but targeted at the `v3` branch.
=> [v3] Enhance PHPdoc of Service write value parameter

CHANGELOG.md, lib/Version.php
I may as well release this little fix while I am working in this repo.
=> Prepare 3.0.2

CHANGELOG.md, lib/Version.php
@clxmstaab or better @staabm ? ;-)
=> Release 4.0.3

lib/Element/Elements.php, lib/Element/KeyValue.php, lib/Element/Uri.php, lib/Element/XmlFragment.php, tests/Sabre/Xml/ServiceTest.php
Backport PRs #258 and #260 to the v3 branch.
=> Backport to v3

tests/phpunit.xml
to be consistent with other sabre repos like
https://github.com/sabre-io/cache/pull/60
https://github.com/sabre-io/uri/pull/105
=> test: add convertDeprecationsToExceptions option to unit test settings

lib/Deserializer/functions.php, lib/LibXMLException.php, lib/Reader.php, lib/Service.php, tests/Sabre/Xml/Element/XmlFragmentTest.php, tests/Sabre/Xml/ServiceTest.php
```
$ composer cs-fixer
> php-cs-fixer fix
PHP CS Fixer 3.54.0 15 Keys Accelerate by Fabien Potencier, Dariusz Ruminski and contributors.
PHP runtime: 7.4.3-4ubuntu2.20
Loaded config default from "/home/phil/git/sabre-io/xml/.php-cs-fixer.dist.php".
40/40 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
1) tests/Sabre/Xml/Element/XmlFragmentTest.php
2) tests/Sabre/Xml/ServiceTest.php
3) lib/Deserializer/functions.php
4) lib/Reader.php
5) lib/LibXMLException.php
6) lib/Service.php
Fixed 6 of 40 files in 2.147 seconds, 20.000 MB memory used
```
=> chore: apply cs-fixer changes to v3 branch

CHANGELOG.md, composer.json, lib/Version.php, tests/Sabre/Xml/WriterTest.php
This release has minor code style changes that were applied by php-cs-fixer major version 3
=> chore: prepare release 2.2.10
